### ISSUE TITLE
build demo 失败

### ISSUE THREAD

**Issue by ouuan** [bhuztez/elaphure#1]
```
$ python run.py generate
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    import elaphure.__main__
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\elaphure\__main__.py", line 60, in <module>
    parser.dispatch()
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\argh\helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\argh\dispatching.py", line 174, in dispatch
    for line in lines:
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\argh\dispatching.py", line 277, in _execute_command
    for line in result:
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\argh\dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\elaphure\__main__.py", line 27, in generate
    scan(cfg, src)
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\elaphure\generator.py", line 76, in scan
    Generator(config, src).scan()
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\elaphure\generator.py", line 54, in scan
    if self.add(filename):
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\elaphure\generator.py", line 45, in add
    self.database.add(filename, reader_name, meta_func(filename, data))
  File "C:\Users\ub\AppData\Local\Programs\Python\Python37\lib\site-packages\elaphure\database.py", line 74, in add
    (filename, reader, json.dumps(metadata)))
sqlite3.OperationalError: no such function: json
```

**Comment by ouuan** [comment]
环境 Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32

**Comment by ouuan** [comment]
在 https://github.com/bhuztez/ojwiki-demo 的根目录下运行的命令。

**Comment by bhuztez** [comment]
这个是因为sqlite没有编译 https://www.sqlite.org/json1.html 扩展

**Comment by bhuztez** [comment]
不应该啊，我是Python 3.7.4

**Comment by bhuztez** [comment]
我看看，说不定可以在Python里把这几个函数实现了

**Comment by bhuztez** [comment]
更新了，暂时先增加了一个DummyRegistry，请试一下看看还有啥问题

**Comment by bhuztez** [comment]
注意，顺便把命令改了，现在用 build 而不是 generate 。这样长的更像 jekyll 一点

**Comment by bhuztez** [comment]
demo已死
